shop/urls.py
from django.urls import path
from .views import (
    remove_from_cart,
    reduce_quantity_item,
    add_to_cart,
    category_products_view,
    tag_products_view,
    category_view,
    checkout_view,
    order_summary_view,
    product_view,
    search_view,
    persists_view,
    cancel_order_view
)
app_name = 'shop'
urlpatterns = [
    path('', category_view, name='home'),
    path('products/<str:slug>/',category_products_view, name='products'),
    path('product-tags/<str:tag>/',tag_products_view, name='tag-view'),
    path('product-details/<str:slug>/',product_view, name='product-details'),
    path('order-summary/', order_summary_view, name='order-summary'),
    path('checkout/', checkout_view, name='checkout'),
    path('persists-data/', persists_view, name='persists'),
    path('search-product/', search_view, name='search'),
    path('add-to-cart/<str:slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<str:slug>/', remove_from_cart, name='remove-from-cart'),
    path('reduce-quantity-item/<str:slug>/', reduce_quantity_item, name='reduce-quantity-item'),
    path('trustkisia/order/cancel-order/<str:order_id>/', cancel_order_view, name='cancel-order')
]

trustkisia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop'))    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title> trustkisia </title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" href="{% static 'css/slick.css' %}">
      <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
      <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">
      <!-- CSS only -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.bootstrap3.min.css" integrity="sha256-ze/OEYGcFbPRmvCnrSeKbRTtjG4vGLHXgOqsyLFTRjg=" crossorigin="anonymous" />
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
   </head>
   <body >
      <div class="social-info shadow-sm">
         <!-- social info -->
         <div class="row text-light">
            <div class=" contact-phone col-lg-4 col-md-4 col-sm-4">
               <p> +254 748613509 </p>
            </div>
            <div class="contact-email col-lg-4 col-md-4 col-sm-4">
               <p>Info@trustkisia.com</p>
            </div>
            <div class="social-links col-lg-4 col-md-4 col-sm-4">
               <i class="fa fa-facebook"></i>
               <i class="fa fa-twitter"></i>
               <i class="fa fa-whatsapp"></i>
               <i class="fa fa-instagram"></i>
            </div>
         </div>
      </div>
      <div class="search-row  mb-2 mt-1" >
         <div class="container">
            <div class="row ">
               <div class="col-lg-1">
               </div>
               <div class="col-lg-2 col-md-2 col-sm-12">
                  <div class="logo mb-2">
                     <!-- logo -->
                     <a href="{% url 'shop:home' %}">
                     <img width="150" src="{% static 'img/logo.png' %}" alt="logo">
                     </a>
                  </div>
               </div>
               <div class="col-lg-6 col-xs-8 col-sm-9 col-xs-offset-2">
                  <div class="search-bar">
                     <div class="input-group">
                        <input type="text" class="form-control" name="x" id="searchBar" placeholder="Search">
                        <span class="btn btn-search">SEARCH</span>
                        <div id="searchList" >
                           <ul id="productList" style="list-style-type: none;"></ul>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-lg-3 col-xs-2 col-sm-2">
                  <div class="cart fa-pull-center">
                     <!-- cart -->
                     <a href="{% url 'shop:order-summary' %}"><i class="fa fa-shopping-cart text-muted"></i><span>Cart</span></a>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div>
         <div class="blur rounded top-0 z-index-3  position-relative start-0 end-0">
            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'success' %}
            <div class="alert alert-success" role="alert">
               {{ message }}
            </div>
            {% elif message.tags == 'info' %}
            <div class="alert alert-info" role="alert">
               {{ message }}
            </div>
            {% else %}
            <div class="alert alert-danger" role="alert">
               {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
         </div>
         <div>
            {% if form.errors %}
            {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger" role="alert">{{ error }}</div>
            {% endfor %}
            {% endfor %}
            {% endif %}
         </div>
      </div>
      {% block content %}
      {% endblock content %}
      {% include "footer.html" %}
      {% include "script.html" %}
      {% block extra_script %}
      <script src="{% static 'js/main.js' %}"></script>
      {% endblock extra_script %}
   </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{%load humanize%}
{% block content %}
<div id="cart-page">
   <div class="cart-section">
      <div class="container">
         <div class="row">
            <div class="col-md-9 cart">
               <div class="title">
                  <div class="row">
                     <div class="col">
                        <h4><b>Shopping Cart</b></h4>
                     </div>
                     <div class="col align-self-center text-right text-muted">{{object.get_total_no_items}} items</div>
                  </div>
               </div>
               {% for product in object.products.all %}
               <div class="row border-top border-bottom">
                  <div class="row main align-items-center">
                     <div class="col"><img class="img-fluid" src="{{product.product.get_product_image_url}}"></div>
                     <div class="col">
                        <div class="row text-muted">{{product.product.name|truncatechars:38}}</div>
                        {% comment %} 
                        <div class="row">short description</div>
                        {% endcomment %}
                     </div>
                     <div class="col">
                        <a href="{% url 'shop:reduce-quantity-item' product.product.slug %}"> - </a>
                        <a href="" class="border">{{product.quantity}}</a>
                        <a href="{% url 'shop:add-to-cart' product.product.slug %}"> + </a>
                     </div>
                     <div class="col">Ksh. {{product.get_final_price|intcomma}}</div>
                     <div class="col">Discount: Ksh. {{product.get_discount_item_price|intcomma}} 
                     </div>
                     <div class="col"><a href="{% url 'shop:remove-from-cart' product.product.slug %}"><span class="close">&#10005;</span></a></div>
                  </div>
               </div>
               {% endfor %}
               <div class="back-to-shop"><a href="{% url 'shop:home' %}" ><span class="">Back to shop</span></a></div>
            </div>
            <div class="col-md-3 summary">
               <div>
                  <h5><b>Summary</b></h5>
               </div>
               <hr>
               <div class="row">
                  <div class="col" style="padding-left:0;">ITEMS {{object.get_total_no_items}}</div>
               </div>
               <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                  <div class="col">TOTAL PRICE</div>
                  <div class="col text-right">Ksh. {{object.get_total_price|intcomma}}</div>
               </div>
               <a href="{% url 'shop:checkout' %}"><button class="btn">CHECKOUT</button></a>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

templates/footer.html
<footer class="fixed-bottom">
    <p>Copyright 2022</p>
</footer>

templates/index.html
{% extends 'base.html' %}
{%load humanize%}
{% block content %}
<main class="container">
   <div class="row">
      <div class="col-lg-4">
         <nav>
            <!-- main navigation -->
            <ul class="cat-menu shadow-sm ">
               {%for key, value in sub_categories.items %}
               <div class="dropend">
                  <li>
                     <a id="dropdownMenuLink"  style="cursor: pointer; padding-right:55px;" data-bs-toggle="dropdown" >{{key}}</a><i style="opacity: 0.2;" class=' text-muted fa fa-angle-down fa-pull-right'></i>
                     <ul class="dropdown-menu position-inherit bg-white border-0 rounded-0 w-100 p-3 m-0" aria-labelledby="dropdownMenuLink">
                        {%for sub_category in value %}
                        <li class="dropdown-item "><a class="nav-link" href="{% url 'shop:products' sub_category.slug %}" target>{{sub_category}}</a></li>
                        {%endfor%}
                     </ul>
                  </li>
               </div>
               {%endfor%}  
            </ul>
         </nav>
      </div>
      <div class="col-lg-8">
         <!-- Carousel -->
         <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
            <ol class="carousel-indicators">
               <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
               <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
               <!-- <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li> -->
            </ol>
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <img class="" height="450" src="../static/img/b1.jpg" alt="First slide">
               </div>
               <div class="carousel-item">
                  <img class="" height="450" src="../static/img/b2.jpg" alt="Second slide">
               </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
         </div>
      </div>
      <div class="col-lg-">
         <!-- poster -->
      </div>
   </div>
</main>
<main class="container ">
   <div class="main-card shadow-sm">
      <div class="product-item">
         <!-- featured products -->
         <main class="container ">
            <h2>Featured <b>Products</b></h2>
            <div class="product-div">
               <!-- Wrapper for carousel items -->
               <div class="item">
                  <section class="row autoplay">
                     {% for product in products %}
                     {% if product.tag == 'Featured' %}
                     <div class="col-lg-3 col-md-3 col-sm-6 p-0">
                        <div class="thumb-wrapper">
                           <div class="img-box">
                              <a href="{%url 'shop:product-details' product.slug %}">
                              <img src="{{product.get_product_image_url}}" class="img-fluid" alt="Macbook"></a>  
                           </div>
                           <div class="thumb-content">
                              <h4>{{product.name | truncatechars:37}}</h4>
                              <p class="item-price"><b>Ksh. {{product.price|intcomma}}</b></p>
                              {% if product.quantity <= 0 %}
                              <p> Out Of Stock </p>
                              {% else %}
                              <a href="{{ product.get_add_to_cart_url }}" class="btn btn-primary">Add to Cart</a>
                              {% endif %}
                           </div>
                        </div>
                     </div>
                     {% endif %}
                     {% endfor %}            								                                           				
                  </section>
               </div>
            </div>
         </main>
      </div>
      <a class="btn-more" href="{% url 'shop:tag-view' 'Featured' %}">More Products</a>
   </div>
</main>
<br>
<main class="container ">
   <div class="main-card shadow-sm">
      <div class="product-item">
         <!-- featured products -->
         <main class="container">
            <h2>Hot Sale <b>Products</b></h2>
            <div class="product-div">
               <!-- Wrapper for carousel items -->
               <div class="item">
                  <section class="row autoplay">
                     {% for product in products %}
                     {% if product.tag == 'Hot Sale' %}
                     <div class="col-lg-3 col-md-3 col-sm-6 p-0">
                        <div class="thumb-wrapper">
                           <div class="img-box">
                              <a href="{%url 'shop:product-details' product.slug %}">
                              <img src="{{product.get_product_image_url}}" class="img-fluid" alt="Macbook"></a>  
                           </div>
                           <div class="thumb-content">
                              <h4>{{product.name | truncatechars:37}}</h4>
                              <p class="item-price"><b>Ksh. {{product.price|intcomma}}</b></p>
                              {% if product.quantity <= 0 %}
                              <p> Out Of Stock </p>
                              {% else %}
                              <a href="{{ product.get_add_to_cart_url }}" class="btn btn-primary">Add to Cart</a>
                              {% endif %}
                           </div>
                        </div>
                     </div>
                     {% endif %}
                     {% endfor %}            								                                           				
                  </section>
               </div>
            </div>
         </main>
      </div>
      <a class="btn-more" href="{% url 'shop:tag-view' 'Hot-Sale' %}">More Products</a>
   </div>
</main>
<br>
<main class="container ">
   <div class="main-card shadow-sm">
      <div class="product-item">
         <!-- featured products -->
         <main class="container">
            <h2>Latest <b>Products</b></h2>
            <div class="product-div">
               <!-- Wrapper for carousel items -->
               <div class="item">
                  <section class="row autoplay">
                     {% for product in products %}
                     {% if product.tag == 'Latest Products' %}
                     <div class="col-lg-3 col-md-3 col-sm-6 p-0">
                        <div class="thumb-wrapper">
                           <div class="img-box">
                              <a href="{%url 'shop:product-details' product.slug %}">
                              <img src="{{product.get_product_image_url}}" class="img-fluid" alt="Macbook"></a>  
                           </div>
                           <div class="thumb-content">
                              <h4>{{product.name | truncatechars:37}}</h4>
                              <p class="item-price"><b>Ksh. {{ product.price|intcomma }}</b></p>
                              {% if product.quantity <= 0 %}
                              <p> Out Of Stock </p>
                              {% else %}
                              <a href="{{ product.get_add_to_cart_url }}" class="btn btn-primary">Add to Cart</a>
                              {% endif %}
                           </div>
                        </div>
                     </div>
                     {% endif %}
                     {% endfor %}            								                                           				
                  </section>
               </div>
            </div>
         </main>
      </div>
      <a class="btn-more" href="{% url 'shop:tag-view' 'Latest-Products' %}">More Products</a>
   </div>
</main>
<br>
<br><br>
{% endblock content %}

templates/product-details.html
{% extends 'base.html' %}
{%load humanize%}
{% block content %}
<div class="container mt-5 mb-5">
   <div class="row d-flex justify-content-center">
      <div class="col-md-10">
         <div class="card">
            <div class="row">
               <div class="col-md-6 mt-5 ">
                  <div class="images p-3 pr-0">
                     <div class="text-center pl-5 mb-4 pt-5 main-product-image"> <img id="imageClickAndChange" src="{{product.get_product_image_url}}" width="400" /></div>
                     <div class="thumbnail text-center">
                        <script>var images = []; </script>
                        {% for image in product.get_all_product_images %}
                        <img class="small-img" src="{{image.image.url}}" width="70">
                        <script>imageUrl =`{{image.image.url}}`; images.push(imageUrl);</script>
                        {% endfor %}
                        <script> console.log(images);</script>
                     </div>
                  </div>
               </div>
               <div class="col-md-6">
                  <div class="product p-4">
                     <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center"> <a href="{%url 'shop:home'%}"><i class="fa fa-long-arrow-left"></i> <span class="ml-1">Back</span></a></div>
                        <a href="{% url 'shop:order-summary' %}"><i class="fa fa-shopping-cart text-muted"></i></a>
                     </div>
                     <div class="mt-4 mb-3">
                        <span class="text-uppercase text-muted brand">BRAND | {{product.brand}}</span>
                        <h5 class="text-uppercase">{{product.name}}</h5>
                        <div class="price d-flex flex-row align-items-center"> <span class="act-price">Ksh. {{product.price|intcomma}}</span>
                        </div>
                     </div>
                     <p class="about">{{product.key_features | safe}}</p>
                     {% if product.quantity <= 0 %}
                     <p>Out Of Stock</p>
                     {% else %}
                     <div class="cart mt-4 align-items-center">
                        <p>{{product.quantity}} in stock </p>
                        <a href="{{ product.get_add_to_cart_url }}">
                        <button class="btn btn-danger text-uppercase mr-2 px-4"> Add to cart <i class="fa fa-shopping-cart"></i></button><a>
                     </div>
                  </div>
                  {% endif %} 
               </div>
            </div>
         </div>
         <div class="card">
            <div class="descr-0">
               <h5>Product Description</h5>
            </div>
            <div class="descr">
               <p>{{product.description | safe}}</p>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{%load humanize%}
{% block content %}
<main class="container">
   <div class="">
      <div class="product-item">
         <!-- featured products -->
         <main class="container">
            <div class="product-div">
               <!-- Wrapper for carousel items -->
               <div class="item">
                  <div class="row">
                     {% for product in products %}
                     <div class="col-lg-3 col-md-4 col-sm-6  p-0">
                        <div class="thumb-wrapper">
                           <div class="img-box">
                              <a href="{%url 'shop:product-details' product.slug %}">
                              <img src="{{product.get_product_image_url}}" class="img-fluid" alt="Macbook"></a>  
                           </div>
                           <div class="thumb-content">
                              <h4>{{product.name | truncatechars:37}}</h4>
                              <p class="item-price"><b>Ksh. {{product.price|intcomma}}</b></p>
                              {% if product.quantity <= 0 %}
                              <p> Out Of Stock </p>
                              {% else %}
                              <a href="{{ product.get_add_to_cart_url }}" class="btn btn-primary">Add to Cart</a>
                              {% endif %}
                           </div>
                        </div>
                     </div>
                     {% endfor %}            								                                           				
                  </div>
               </div>
            </div>
         </main>
      </div>
   </div>
</main>
<br>
{% endblock content %}

templates/script.html
{% load static %}
<script src="https://kit.fontawesome.com/415119f36a.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha256-+C0A5Ilqmu4QcSPxrlGpaZxJ04VjsRjKu+G82kl5UJk=" crossorigin="anonymous"></script>
<script>
var imageState = 0;
var imageTag = document.getElementById('imageClickAndChange');
imageTag.addEventListener("click", function (event) {
    imageState = (++imageState % images.length);
    event.target.src = images[imageState];
});
</script>
<script>
    $ (document).ready(function () {
        const productList = document.getElementById('productList');
        const searchBar = document.getElementById('searchBar');
        let allProducts = [];
        searchBar.addEventListener('keyup', (e) => {
            var x = document.getElementById('searchList')
            const searchString = e.target.value.toLowerCase();
            const filteredProducts = allProducts.filter((product) => {
                return (
                    product.fields.name.toLowerCase().includes(searchString) ||
                    product.fields.brand.toLowerCase().includes(searchString)
                );
            });
            displayProducts(filteredProducts, searchString);
        });
        const loadProducts = async () => {
            try {
                const res = await fetch('{% url "shop:search" %}');
                allProducts = await res.json();
            } catch (err) {
                console.error(err);
            }
        };
        const displayProducts = (products, searchString) => {
            const htmlString = products
                .map((product) => {
                    url = `http://127.0.0.1:8000/product-details/${product.fields.slug}`
                    return `
                    <a href="${url}" class="text-dark fw-normal" style="text-decoration: none;">
                        <li>
                        <p>${product.fields.name}</p></li><hr>
                    </a>
                `;
                })
                .join('');
            productList.innerHTML = htmlString;

            if (searchString.length === 0) {
                productList.innerHTML = '';
            }
        };
        loadProducts();

    // Setting the device cookie
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')){
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    function uuidv4() {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }
    $.ajax({
        url: "{% url 'shop:persists' %}",
        // on success
        success: function (response) {
            boolvalue = response
            
            if (boolvalue['value'] == true)  {
                let device = getCookie('device')
                device = uuidv4()
                document.cookie = 'device=' + device + ";domain=;path=/"   
            }  
        },
        // on error
        error: function (response) {
            // alert the error if any error occured
            console.log(response.responseJSON.errors)
        }
    });
    device = getCookie('device')
    if (device == null || device == undefined) {
        device = uuidv4()
    }
    document.cookie = 'device=' + device + ";domain=;path=/"  

    $('select').selectize({
        sortField: 'text'
    });
      var jq = jQuery.noConflict();
      jq( document ).ready(function( $ ) {
        var alterClass = function() {
          var ww = document.body.clientWidth;
          if (ww < 600) {
            $('body, html, main').removeClass('container');
            $('section').removeClass('autoplay');
            $('section').addClass('autoplay-sm');
                window.autoplay = 'autoplay-sm';
          } else if (ww >= 992) {
            $('body, html, main').addClass('container');
            $('section').removeClass('autoplay-sm');
            $('section').addClass('autoplay');
            window.autoplay = 'autoplay';
          };
        }
        $(window).resize(function(){
          alterClass();
        });
        //Fire it when the page first loads:
        alterClass();
        console.log(window.autoplay)
        if (window.autoplay === 'autoplay-sm'){
            $('.autoplay-sm').slick({
                slidesToShow: 2,
                slidesToScroll: 2,
                autoplay: true,
                autoplaySpeed: 2450,
              });
        } else {
            $('.autoplay').slick({
                slidesToShow: 4,
                slidesToScroll: 1,
                autoplay: true,
                autoplaySpeed: 2500,
              });
        }
      });
    });
</script>    

templates/success-order-cancel.html
{% extends 'base.html' %}
{% block content %}
<section class="main-content">
   <div class="container">
      <div class="row">
         <div class="col-lg-12 col-sm-6 col-md-4">
            <div class="info-card info-card--success">
               <div class="info-card_icon">
                  <img class="info-card_img-icon" src="../static/img/success.svg" alt="success">
               </div>
               <h2 class="info-card_label">Order Cancelled Successfully</h2>
               <div class="info-card_message">Continue shopping with us!</div>
               <a href="{% url 'shop:home' %}"><button class="btn btn-success px-5">Continue</button></a>
            </div>
         </div>
      </div>
   </div>
</section>
{% endblock content %}

templates/success.html
{% extends 'base.html' %}
{% block content %}
<section class="main-content">
   <div class="container">
      <div class="row">
         <div class="col-lg-12 col-sm-6 col-md-4">
            <div class="info-card info-card--success">
               <div class="info-card_icon">
                  <img class="info-card_img-icon" src="../static/img/success.svg" alt="success">
               </div>
               <h2 class="info-card_label">Order Successful</h2>
               <div class="info-card_message">Continue shopping with us!</div>
               <a href="{% url 'shop:home' %}"><button class="btn btn-success px-5">Continue</button></a>
            </div>
         </div>
      </div>
   </div>
</section>
{% endblock content %}